---
name: 04 📦 Publish packages

# yamllint disable-line rule:truthy
on:
  repository_dispatch:
    types: [ publish-packages ]

permissions:
  contents: read
  packages: write

jobs:
  publish-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Needed for commit range checks
          ref: main  # check out the branch, not detached HEAD
      - uses: ./.github/actions/tools
      - run: |
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>get-forge</username>
                <password>${{ secrets.PAT_FORGE_DEPLOY }}</password>
              </server>
            </servers>
          </settings>
          EOF
      - run: task build:deploy
      - run: .github/scripts/publish-summary.sh
