---
name: '100 🗄️ OWASP cache'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Sunday 00:00 UTC

permissions:
  contents: read
  packages: read
  actions: write

env:
  NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
  OSS_INDEX_USER: ${{ secrets.OSS_INDEX_USER }}
  OSS_INDEX_API_KEY: ${{ secrets.OSS_INDEX_API_KEY }}

jobs:
  owasp-dependency-check-cache:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/tools
      - uses: actions/cache@v5
        with:
          path: .dependency-check-cache
          key: dependency-check-${{ runner.os }}-v1
          restore-keys: |
            dependency-check-${{ runner.os }}-

      - run: task build:owasp

      - uses: actions/cache/save@v5
        if: success()
        with:
          path: .dependency-check-cache
          key: dependency-check-${{ runner.os }}-v1
