---
name: 99 🚽 Janitor history cleanup
# yamllint disable-line rule:truthy
on:
  # Run weekly, Sunday afternoon PST
  schedule:
    - cron: '0 23 * * 0'

jobs:
  delete_history:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: get-forge/forge-kit
          retain_days: 7
          keep_minimum_runs: 1
